### ISSUE TITLE
User can subscribe to receive free games several times

### ISSUE THREAD

**Issue by zendet** [etaxi341/FreeSteamGames-TelegramBot#4]
![bug](https://user-images.githubusercontent.com/63907048/182216968-2abcd184-5f9c-4750-8d08-414125db3eda.jpg)
Somehow I got two messages about a free game. That is, the bot **doesn't have a check for an existing subscription** on receiving "free games".

**Comment by etaxi341** [comment]
Hi, I've been looking into this bug for a while...
I have not figured it out yet.
When debugging everything works. But when it runs on the server it does send everything twice... And it's not the exe running twice. I have tried fixing this in previous commits but it does not seem to have fixed it.
I will have a closer look at it again.

**Comment by etaxi341** [comment]
I think it is fixed from now on. Looks like my pc was just faster than the server so it was completed before it had to restart the queue.

**Comment by zendet** [comment]
nice
