### ISSUE TITLE
Is the telegram bot still working?

### ISSUE THREAD

**Issue by robotrono** [etaxi341/FreeSteamGames-TelegramBot#8]
I added the telegram bot to a group of friends, it worked perfectly, but since a few weeks ago it stopped working, since August 3 it no longer gave notifications. 

I appreciate the functionality of the bot.

**Comment by etaxi341** [comment]
Hey @robotrono 

It should still be working. When you look at https://steamdb.info/upcoming/free/ you can see that there are no free promotions currently.
There are only two games that have a free weekend and no game that is free to add to the library.

I personally have set the bot for me to only send games and not DLCs and my last message is from July 24th for the Dungeon of the ENDLESS

**Comment by etaxi341** [comment]
Ok I checked the code again. It definitely is working. It crawls this API from Steam: https://store.steampowered.com/search/results/?force_infinite=1&maxprice=free&specials=1&l=en-US&json=1

Also when checking out the subreddit https://www.reddit.com/r/FreeGamesOnSteam/top/?t=month you can see the last free DLC on Steam was on August 3rd.
